== Environment

=== Lab environment

The lab environment provides a virtualized setup for developing and running Red Hat Enterprise Linux 8.
It consists of:

* A workstation running RHEL 8;

During the lab you will interact through the bash shell from your personal workstation.

The lab instructor will provide a URL via which you will obtain a GUID for the RHEL 8 workstation you are going to use:

|===
| Machine | URL | Access
| Workstation | `rhel8lab-<GUID>.rhpds.opentlc.com` | SSH (port 22)
| SSH to the Workstation Bash Shell | `ssh student@rhel8lab-<GUID>.rhpds.opentlc.com` | SSH (port 22)
|===

[NOTE]
.Remember that to connect to your lab you must use the `rhel8lab-<GUID>.rhpds.opentlc.com`. In the lab we we will be referencing this host as workstation.example.com

Every lab assumes that you have access to the workstation via SSH for CLI interaction.

Before you start any lab, make sure you are logged into the workstation via SSH.

The password will be provided by the instructors.

[NOTE]
.Remember your GUID
At the start of the lab you have been provided with a GUID, which uniquely identifies your lab environment.
In the following instructions, replace the `<GUID>` placeholder with your GUID.
For example, if your GUID is `a2b3`, the URL `workstation-<GUID>.example.com` becomes `workstation-a2b3.example.com`.

Now, let's start the lab.
